function org_vaadin_peter_contextmenu_ContextmenuWidgetset(){var Z='',W=' top: -1000px;',ub='" for "gwt:onLoadErrorFn"',sb='" for "gwt:onPropertyErrorFn"',db='");',vb='#',Zb='.cache.js',xb='/',Db='//',Sb='02589EA6B141086D43E5607B5946FEA7',Tb='053DF16D2430E4EC9DE22B6C6D275ED7',Ub='2A7FECAF89740EB4CB99ABDDD53EF7A9',Yb=':',mb='::',jc=':moduleBase',Y='<!doctype html>',$='<html><head><\/head><body><\/body><\/html>',pb='=',wb='?',Vb='A8003372EA30ACCA75774436B1C6CC53',rb='Bad handler "',Wb='CBB837F7D3DF715C9CAD7A3AC50A32E2',Xb='CE54D2EF2BC91BDA0B3785551FF43582',X='CSS1Compat',bb='Chrome',ab='DOMContentLoaded',R='DUMMY',ic='__gwtDevModeHook:org.vaadin.peter.contextmenu.ContextmenuWidgetset',Cb='base',Ab='baseUrl',M='begin',S='body',L='bootstrap',zb='clear.cache.gif',ob='content',dc='contextmenu-widget/contextmenu.css',fc='end',cb='eval("',hc='file:',Nb='gecko',Ob='gecko1_8',N='gwt.codesvr.org.vaadin.peter.contextmenu.ContextmenuWidgetset=',O='gwt.codesvr=',tb='gwt:onLoadErrorFn',qb='gwt:onPropertyErrorFn',nb='gwt:property',ib='head',bc='href',gc='http:',Jb='ie10',Mb='ie6',Lb='ie8',Kb='ie9',T='iframe',yb='img',fb='javascript',U='javascript:""',$b='link',cc='loadExternalRefs',jb='meta',hb='moduleRequested',gb='moduleStartup',Ib='msie',kb='name',Fb='opera',P='org.vaadin.peter.contextmenu.ContextmenuWidgetset',Rb='org.vaadin.peter.contextmenu.ContextmenuWidgetset.devmode.js',Bb='org.vaadin.peter.contextmenu.ContextmenuWidgetset.nocache.js',lb='org.vaadin.peter.contextmenu.ContextmenuWidgetset::',V='position:absolute; width:0; height:0; border:none; left: -1000px;',_b='rel',Hb='safari',ec='scaleimage/styles.css',eb='script',Qb='selectingPermutation',Q='startup',ac='stylesheet',_='undefined',Pb='unknown',Eb='user.agent',Gb='webkit';var o=window;var p=document;r(L,M);function q(){var a=o.location.search;return a.indexOf(N)!=-1||a.indexOf(O)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:P,sessionId:o.__gwtStatsSessionId,subSystem:Q,evtGroup:a,millis:(new Date).getTime(),type:b})}}
org_vaadin_peter_contextmenu_ContextmenuWidgetset.__sendStats=r;org_vaadin_peter_contextmenu_ContextmenuWidgetset.__moduleName=P;org_vaadin_peter_contextmenu_ContextmenuWidgetset.__errFn=null;org_vaadin_peter_contextmenu_ContextmenuWidgetset.__moduleBase=R;org_vaadin_peter_contextmenu_ContextmenuWidgetset.__softPermutationId=0;org_vaadin_peter_contextmenu_ContextmenuWidgetset.__computePropValue=null;org_vaadin_peter_contextmenu_ContextmenuWidgetset.__getPropMap=null;org_vaadin_peter_contextmenu_ContextmenuWidgetset.__gwtInstallCode=function(){};org_vaadin_peter_contextmenu_ContextmenuWidgetset.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[P]={moduleName:P};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(S)[0]}
function y(){if(v){return}var a=p.createElement(T);a.src=U;a.id=P;a.style.cssText=V+W;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==X?Y:Z;v.write(b+$);v.close()}
function z(k){function l(a){function b(){if(typeof p.readyState==_){return typeof p.body!=_&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(ab,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(ab,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(bb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(cb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(db));g=f.createElement(eb);g.language=fb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(eb);g.language=fb;g.text=c[i];e.appendChild(g);d(e,g)}}}
org_vaadin_peter_contextmenu_ContextmenuWidgetset.onScriptDownloaded=function(a){l(function(){m(a)})};r(gb,hb);var n=p.createElement(eb);n.src=k;p.getElementsByTagName(ib)[0].appendChild(n)}
org_vaadin_peter_contextmenu_ContextmenuWidgetset.__startLoadingFragment=function(a){return C(a)};org_vaadin_peter_contextmenu_ContextmenuWidgetset.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(eb);c.language=fb;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(jb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(kb),k;if(j){j=j.replace(lb,Z);if(j.indexOf(mb)>=0){continue}if(j==nb){k=i.getAttribute(ob);if(k){var l,m=k.indexOf(pb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=Z}c[j]=l}}else if(j==qb){k=i.getAttribute(ob);if(k){try{d=eval(k)}catch(a){alert(rb+k+sb)}}}else if(j==tb){k=i.getAttribute(ob);if(k){try{e=eval(k)}catch(a){alert(rb+k+ub)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;org_vaadin_peter_contextmenu_ContextmenuWidgetset.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(vb);if(b==-1){b=a.length}var c=a.indexOf(wb);if(c==-1){c=a.length}var d=a.lastIndexOf(xb,Math.min(c,b));return d>=0?a.substring(0,d+1):Z}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(yb);b.src=a+zb;a=e(b.src)}return a}
function g(){var a=t(Ab);if(a!=null){return a}return Z}
function h(){var a=p.getElementsByTagName(eb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Bb)!=-1){return e(a[b].src)}}return Z}
function i(){var a=p.getElementsByTagName(Cb);if(a.length>0){return a[a.length-1].href}return Z}
function j(){var a=p.location;return a.href==a.protocol+Db+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==Z){k=h()}if(k==Z){k=i()}if(k==Z&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return org_vaadin_peter_contextmenu_ContextmenuWidgetset.__moduleBase+a}
function D(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Eb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Fb)!=-1}())return Fb;if(function(){return b.indexOf(Gb)!=-1}())return Hb;if(function(){return b.indexOf(Ib)!=-1&&p.documentMode>=10}())return Jb;if(function(){return b.indexOf(Ib)!=-1&&p.documentMode>=9}())return Kb;if(function(){return b.indexOf(Ib)!=-1&&p.documentMode>=8}())return Lb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Mb;if(function(){return b.indexOf(Nb)!=-1}())return Ob;return Pb};i[Eb]={gecko1_8:0,ie10:1,ie6:2,ie8:3,ie9:4,opera:5,safari:6};s=function(a,b){return b in i[a]};org_vaadin_peter_contextmenu_ContextmenuWidgetset.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};org_vaadin_peter_contextmenu_ContextmenuWidgetset.__computePropValue=k;o.__gwt_activeModules[P].bindings=org_vaadin_peter_contextmenu_ContextmenuWidgetset.__getPropMap;r(L,Qb);if(q()){return C(Rb)}var l;try{h([Jb],Sb);h([Lb],Tb);h([Ob],Ub);h([Fb],Vb);h([Kb],Wb);h([Hb],Xb);l=f[k(Eb)];var m=l.indexOf(Yb);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}org_vaadin_peter_contextmenu_ContextmenuWidgetset.__softPermutationId=g;return C(l+Zb)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement($b);b.setAttribute(_b,ac);b.setAttribute(bc,C(a));p.getElementsByTagName(ib)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(cc,M);c(dc);c(ec);r(cc,fc)}
A();org_vaadin_peter_contextmenu_ContextmenuWidgetset.__moduleBase=B();u[P].moduleBase=org_vaadin_peter_contextmenu_ContextmenuWidgetset.__moduleBase;var F=D();if(o){var G=!!(o.location.protocol==gc||o.location.protocol==hc);o.__gwt_activeModules[P].canRedirect=G;if(G){var H=ic;var I=o.sessionStorage[H];if(I&&!o[H]){o[H]=true;o[H+jc]=B();var J=p.createElement(eb);J.src=I;var K=p.getElementsByTagName(ib)[0];K.insertBefore(J,K.firstElementChild||K.children[0]);return false}}}E();r(L,fc);z(F);return true}
org_vaadin_peter_contextmenu_ContextmenuWidgetset.succeeded=org_vaadin_peter_contextmenu_ContextmenuWidgetset();